linters:
  enable:
    - errcheck
    - unused
    - typecheck
  disable:
    - ineffassign  # Disable ineffassign - слишком строгий для тестов

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - ineffassign

run:
  timeout: 5m
  tests: true
