linters:
  enable:
    - errcheck
    - unused
    - typecheck
  disable:
    - ineffassign
    - staticcheck  # Disable SA4006 warnings

linters-settings:
  errcheck:
    check-blank: false  # Allow _ = assignments
    check-type-assertions: false

issues:
  exclude-rules:
    # Отключаем errcheck и staticcheck для всех тестовых файлов
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign
        - staticcheck
    # Отключаем errcheck для файлов с nolint комментариями
    - linters:
        - errcheck
      text: "Error return value.*is not checked"

run:
  timeout: 5m
  tests: true
