// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: fraud.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckTransactionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SourceWalletId      string                 `protobuf:"bytes,2,opt,name=source_wallet_id,json=sourceWalletId,proto3" json:"source_wallet_id,omitempty"`
	DestinationWalletId string                 `protobuf:"bytes,3,opt,name=destination_wallet_id,json=destinationWalletId,proto3" json:"destination_wallet_id,omitempty"`
	Amount              string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency            string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionType     string                 `protobuf:"bytes,6,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // TRANSFER, EXCHANGE, DEPOSIT, WITHDRAWAL
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckTransactionRequest) Reset() {
	*x = CheckTransactionRequest{}
	mi := &file_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTransactionRequest) ProtoMessage() {}

func (x *CheckTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTransactionRequest.ProtoReflect.Descriptor instead.
func (*CheckTransactionRequest) Descriptor() ([]byte, []int) {
	return file_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckTransactionRequest) GetSourceWalletId() string {
	if x != nil {
		return x.SourceWalletId
	}
	return ""
}

func (x *CheckTransactionRequest) GetDestinationWalletId() string {
	if x != nil {
		return x.DestinationWalletId
	}
	return ""
}

func (x *CheckTransactionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CheckTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CheckTransactionRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

type CheckTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // 0.0 (safe) to 1.0 (fraud)
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                          // human-readable reason if rejected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTransactionResponse) Reset() {
	*x = CheckTransactionResponse{}
	mi := &file_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTransactionResponse) ProtoMessage() {}

func (x *CheckTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTransactionResponse.ProtoReflect.Descriptor instead.
func (*CheckTransactionResponse) Descriptor() ([]byte, []int) {
	return file_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTransactionResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *CheckTransactionResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *CheckTransactionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_fraud_proto protoreflect.FileDescriptor

const file_fraud_proto_rawDesc = "" +
	"\n" +
	"\vfraud.proto\x12\bfraud.v1\"\xef\x01\n" +
	"\x17CheckTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10source_wallet_id\x18\x02 \x01(\tR\x0esourceWalletId\x122\n" +
	"\x15destination_wallet_id\x18\x03 \x01(\tR\x13destinationWalletId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12)\n" +
	"\x10transaction_type\x18\x06 \x01(\tR\x0ftransactionType\"m\n" +
	"\x18CheckTransactionResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2r\n" +
	"\x15FraudDetectionService\x12Y\n" +
	"\x10CheckTransaction\x12!.fraud.v1.CheckTransactionRequest\x1a\".fraud.v1.CheckTransactionResponseB:Z8github.com/Haleralex/wallethub/internal/adapters/grpc/pbb\x06proto3"

var (
	file_fraud_proto_rawDescOnce sync.Once
	file_fraud_proto_rawDescData []byte
)

func file_fraud_proto_rawDescGZIP() []byte {
	file_fraud_proto_rawDescOnce.Do(func() {
		file_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fraud_proto_rawDesc), len(file_fraud_proto_rawDesc)))
	})
	return file_fraud_proto_rawDescData
}

var file_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fraud_proto_goTypes = []any{
	(*CheckTransactionRequest)(nil),  // 0: fraud.v1.CheckTransactionRequest
	(*CheckTransactionResponse)(nil), // 1: fraud.v1.CheckTransactionResponse
}
var file_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.v1.FraudDetectionService.CheckTransaction:input_type -> fraud.v1.CheckTransactionRequest
	1, // 1: fraud.v1.FraudDetectionService.CheckTransaction:output_type -> fraud.v1.CheckTransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fraud_proto_init() }
func file_fraud_proto_init() {
	if File_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fraud_proto_rawDesc), len(file_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fraud_proto_goTypes,
		DependencyIndexes: file_fraud_proto_depIdxs,
		MessageInfos:      file_fraud_proto_msgTypes,
	}.Build()
	File_fraud_proto = out.File
	file_fraud_proto_goTypes = nil
	file_fraud_proto_depIdxs = nil
}
